[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[lib]
name = "runtime"
path = "src/lib.rs"

[dependencies]
either = "1.11.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
