// this file is autogenerated, do not edit manually
// to change this file consult gen/genall.sh
#[repr(u8)]
#[derive(Debug)]
pub enum Opcode {
    NOP = 0,
    DUP = 1,
    SWAP = 2,
    POP = 3,
    PUSH = 4,
    FLOOKUP = 5,
    TLOOKUP = 6,
    CALL = 7,
    TYPEOF = 8,
    FROMSLOT = 9,
    TOSLOT = 10,
    ADD = 11,
    SUB = 12,
    EQ = 13,
    LT = 14,
    GT = 15,
    AND = 16,
    OR = 17,
    I2B = 18,
    I2F = 19,
    NOT = 20,
    JUMP = 21,
    JTRUE = 22,
    RET = 23,
    MKARRTYPE = 24,
    MKRECTYPE = 25,
    NEWARR = 26,
    ARRGET = 27,
    ARRSET = 28,
    ARRLEN = 29,
    NEWREC = 30,
    RECGET = 31,
    RECSET = 32,
    MAX,
}
impl From<u8> for Opcode {
    fn from(value: u8) -> Self {
        let max = unsafe { std::mem::transmute(Opcode::MAX) };
        if value >= max {
            panic!("invalid opcode {value}")
        }
        unsafe { std::mem::transmute(value) }
    }
}
impl From<Opcode> for u8 {
    fn from(value: Opcode) -> Self {
        unsafe { std::mem::transmute(value) }
    }
}
