// this file is autogenerated, do not edit manually
// to change this file consult gen/genall.sh
#[repr(u8)]
#[derive(Debug)]
pub enum Opcode {
    NOP,
    DUP,
    SWAP,
    POP,
    PUSH,
    FLOOKUP,
    TLOOKUP,
    CALL,
    TYPEOF,
    FROMSLOT,
    TOSLOT,
    ADD,
    SUB,
    EQUAL,
    NOT,
    JUMP,
    JTRUE,
    RET,
    MKARRTYPE,
    MKRECTYPE,
    NEWARR,
    ARRGET,
    ARRSET,
    ARRLEN,
    NEWREC,
    RECGET,
    RECSET,
    MAX,
}
impl From<u8> for Opcode {
    fn from(value: u8) -> Self {
        unsafe {
            if value >= std::mem::transmute(Opcode::MAX) {
                panic!("invalid opcode {value}")
            } else {
                std::mem::transmute(value)
            }
        }
    }
}
impl From<Opcode> for u8 {
    fn from(value: Opcode) -> Self {
        unsafe { std::mem::transmute(value) }
    }
}
